name: smooth_page_indicator
description: Customizable animated page indicator with a set of built-in effects.
version: 1.1.0
homepage: https://github.com/Milad-Akarie/smooth_page_indicator

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
